### ISSUE TITLE
Change and Input events are not triggering(Need help urgently)

### ISSUE THREAD

**Issue by YakupIpek** [tempusdominus/bootstrap-3#28]
I was trying to bind value to my model by knockout.js and i realized that model was not updating itself after date is changed then i realized that change and input events aren't triggering even. 

Please take a look at example. https://jsfiddle.net/0Ltv25o8/5649/
Try pick a date and you will not get alert on change and input events. 

I have also tested it on version 5 and it has still same issue. 

Can you please tell me at least how can i fix this issue temporarily ?

**Comment by webRaaj** [comment]
Sorry but facing similar issue.

**Comment by William-H-M** [comment]
Hi, the plugin doesn't fire the change event, because, if not wrong, it does a `e.preventDefault`, but you can know if the date was changed using `dp.change` event for the older release or for this current project use 
[change.datetimepicker](https://tempusdominus.github.io/bootstrap-3/Events/#changedatetimepicker)

And that way you'll know that a change was made.

Now, as this question is:
1) A 'How to....' question
2) The fiddle gave is of the [other plugin](https://github.com/Eonasdan/bootstrap-datetimepicker)
This issue should be closed, thanks.

**Comment by YakupIpek** [comment]
Many libraries like attach handler for change event and this library prevent default action. Now my validations and other libraries couldn't handle change event. This is quite wrong to bypass change event. 

Custom dp.change event is not valid solution. I guess this is designed this way just because to bind model property as Date object instead of string for angular,knockout.js...etc but many libraries rely on native events. 

This issue should not be closed.

**Comment by William-H-M** [comment]
@YakupIpek Hi, for this library the input DOES works and many libraries rely on 'input event' as this is triggered before all others [[spec](https://www.w3.org/TR/html5/forms.html#send-select-update-notifications)]

You can test that the input event currently work, as per the change event should be checked as with change.datetimepicker.
https://jsfiddle.net/Eonasdan/agbkdzhv/
On the fiddle above paste this code:
 
```
$('#datetimepicker1').on('input', function() {
   alert("Hey there :)")
 });
 $('#datetimepicker1').on('change', function() {
   alert("Hey there, I won't trigger :(");
 });

```

**Comment by YakupIpek** [comment]
Yes input event works and but doesn't work for old library. I want to know that why you prevent default change event ? What is reason of it ? Imo this is quite wrong thing to do.

**Comment by William-H-M** [comment]
Hi, @YakupIpek yes for older library is not working because is not being implemented, but is for this repo that's a new version and is being improved. The issue is for this repo not the older one, for the older you'll have to implement what's being done here.

> I want to know that why you prevent default change event 

For this part I'm NOT totally sure if an actual `e.preventDefault()` is being used this is something that I'm guessing

**Comment by Gyyone** [comment]
It work for me.      
$("#datetimeid").on('change.datetimepicker', function (change, viewDate) {
            alert("date change");

        });

**Comment by clockover** [comment]
> 
> 
> Yes input event works and but doesn't work for old library. I want to know that why you prevent default change event ? What is reason of it ? Imo this is quite wrong thing to do.

I confirm it's a bad way to do.
